<?php
session_start();
if(!session_is_registered(myusername)){
    header("location:index.php");
}
include("include/header.php.inc");
include_once('config/db.php.inc');
 
echo "<form action=\"session.php\" method=\"POST\" accept-charset=\"utf-8\">\n";


echo "<table width=\"1024\" border=\"1\">\n";
echo "      <tr>\n";
echo "            <td>\n";
echo "                  <table width=\"1024\" border=\"0\">\n";
echo "                        <tr>\n";
echo "                              <td>Session title: </td>\n";
echo "                              <td><input type=\"text\" size=\"133\" value=\"\" name=\"title\"></td>\n";
echo "                        </tr>\n";
echo "                        <tr>\n";
echo "                              <td>Tester: </td>\n";
echo "                              <td>\n";
echo "                                  <select name=\"tester\">\n";
echo "                                      <option>TesterName</option>\n";
echo "                                  </select>\n";
echo "                              </td>\n";
echo "                        </tr>\n";
echo "                        <tr>\n";
echo "                              <td>Team: </td>\n";
echo "                              <td>\n";
echo "                                  <select name=\"tester\">\n";
echo "                                      <option>TeamName</option>\n";
echo "                                  </select>\n";
echo "                              </td>\n";
echo "                        </tr>\n";
echo "                        <tr>\n";
echo "                              <td>Sprint: </td>\n";
echo "                              <td>\n";
echo "                                  <select name=\"sprint\">\n";
echo "                                      <option>SprintName</option>\n";
echo "                                  </select>\n";
echo "                              </td>\n";
echo "                        </tr>\n";
echo "                        <tr>\n";
echo "                              <td>Mission: </td>\n";
echo "                              <td>\n";
echo "                                  <textarea id=\"textarea1\" name=\"mission\" style=\"width:1024px;height:200px;\">\n";
echo "                                  </textarea>\n";
echo "                              </td>\n";
echo "                        </tr>\n";
echo "                        <tr>\n";
echo "                              <td>Notes: </td>\n";
echo "                              <td>\n";
echo "                                  <textarea id=\"textarea2\" name=\"notes\" style=\"width:1024px;height:200px;\">\n";
echo "                                  </textarea>\n";
echo "                              </td>\n";
echo "                        </tr>\n";
echo "                        <tr>\n";
echo "                              <td>Metrics: </td>\n";
echo "                              <td>\n";
echo "                                    <table width=\"1024\" border=\"1\">\n";
echo "                                          <tr>\n";
echo "                                                <td>Setup: </td>\n";
echo "                                                <td>\n";
echo "                                                      <select name=\"tester\">\n";
echo "                                                          <option>TeamName</option>\n";
echo "                                                      </select>\n";
echo "                                                </td>\n";
echo "                                                <td>Test: </td>\n";
echo "                                                <td>\n";
echo "                                                      <select name=\"tester\">\n";
echo "                                                          <option>TeamName</option>\n";
echo "                                                      </select>\n";
echo "                                                </td>\n";
echo "                                                <td>Bug: </td>\n";
echo "                                                <td>\n";
echo "                                                      <select name=\"tester\">\n";
echo "                                                          <option>TeamName</option>\n";
echo "                                                      </select>\n";
echo "                                                </td>\n";
echo "                                                <td>Oppertunity: </td>\n";
echo "                                                <td>\n";
echo "                                                      <select name=\"tester\">\n";
echo "                                                          <option>TeamName</option>\n";
echo "                                                      </select>\n";
echo "                                                </td>\n";
echo "                                                <td>Session duration: </td>\n";
echo "                                                <td>\n";
echo "                                                      <select name=\"tester\">\n";
echo "                                                          <option>TeamName</option>\n";
echo "                                                      </select>\n";
echo "                                                </td>\n";
echo "                                          </tr>\n";
echo "                                    </table>\n";
echo "                              </td>\n";
echo "                        </tr>\n";
echo "                  </table>\n";
echo "            </td>\n";
echo "      </tr>\n";
echo "</table>\n";

echo "  <p><input type=\"submit\" value=\"Save\" /></p>\n";
echo "</form>\n";

include("include/footer.php.inc");