<?php 
echo "<br><br><br><br>\n";
echo "<img src=\"pictures/line.png\" alt=\"line\"/>\n";
echo "<br><h6>";
echo "<a href=\"about.php\"id=\"url_about\">About</a> | ";
echo "<a href=\"http://code.google.com/p/sessionweb/\" id=\"url_google_code_sessionweb\">Project Home Page</a> | ";
echo "<a href=\"http://code.google.com/p/sessionweb/issues/list\" id=\"url_submintbug\">Submit a bug report</a></h6><br>\n";
echo "  </body>\n";
echo "</html>\n";

?>