<?php
define("ITEM_ADDED", 0);
define("ITEM_ALREADY_EXIST", 1);
define("ITEM_NOT_ADDED", 2);
define("ITEM_NOT_PROVIDED_IN_REQUEST", 3);
define("UNAUTHORIZED", 4);
define("ITEM_REMOVED", 5);
define("SQL_ERROR", 6);
define("Ok", 7);
define("ITEM_NOT_REMOVED", 8);
define("PASSWORD_DOES_NOT_MATCH", 9);
define("PARAMETER_NOT_PROVIDED_IN_REQUEST", 10);
define("ITEM_NOT_UPDATED", 11);
define("ITEM_UPDATED", 12);
define("CORRECT_PARAMETER_NOT_PROVIDED_IN_REQUEST", 13);
define("USER_ALREADY_EXIST", 14);





?>